CREATE TABLE IF NOT EXISTS TBL_USER (
  ID INT AUTO_INCREMENT PRIMARY KEY ,
  NAME VARCHAR(64) COMMENT '用户姓名',
  MOBILE CHAR(11) NOT NULL COMMENT '用户手机',
  PASSWORD CHAR(64) COMMENT '用户密码',
  CTIME DATETIME NOT NULL COMMENT '注册时间'
);