-- 用户表
CREATE TABLE TBL_USER (
  ID INT AUTO_INCREMENT PRIMARY KEY ,
  NAME VARCHAR(32) COMMENT '用户姓名' ,
  MOBILE CHAR(11) COMMENT '用户手机' ,
  EMAIL VARCHAR(128) COMMENT '用户邮箱' ,
  PASSWORD CHAR(64) COMMENT '用户密码，使用SHA-256加密' ,
  CTIME DATETIME COMMENT '用户创建时间'
) ;

-- 图书表
CREATE TABLE TBL_BOOK (
  ID INT AUTO_INCREMENT PRIMARY KEY ,
  NAME VARCHAR(256) COMMENT '图书名称' ,
  ISBN CHAR(13) COMMENT '图书ISBN号：图书产品代码“978”，组号(国家、地区、语言的代号)，出版者号，书序号和检验码几部分共同组成' ,
  PRICE FLOAT COMMENT '图书定价' ,
  CTIME DATETIME COMMENT '图书录入时间'
) ;

-- 借书表
CREATE TABLE TBL_BORROW (
  ID INT AUTO_INCREMENT PRIMARY KEY ,
  USER_ID INT COMMENT '借书人用户ID' ,
  BOOK_ID INT COMMENT '借出图书ID' ,
  CTIME DATETIME COMMENT  '借书时间' ,
  DURING INT COMMENT '借书时间时，单位：秒' ,
  RETURN_TIME DATETIME COMMENT '归还时间(实际)'
) ;
